spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/CRUD
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  data:
    rest:
      base-path: /api
      detection-strategy: annotated

logging.level:
  org.hibernate.SQL: debug

